name = "abr-geocoder-workers"
compatibility_date = "2024-09-08"
compatibility_flags = [ "nodejs_compat" ]


[[d1_databases]]
binding = "DB"
database_name = "abr-geocoder"
database_id = "test"
preview_database_id = "local-test-db"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"


# [ai]
# binding = "AI"